### ISSUE TITLE
URGENT!!! tx_news and other elements not working aymore after last UPDATE of EXT:netc_bakershop

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakershop#32]
After installing the last version of the EXT:netc_bakershop NO ONE can anymore add, modify or edit a new tx_news item, or creating, editing or deleting a shortcut in TYPO3 or adding content elements like a cTYPE anymore! Even no more Plug-Ins can be added, mofified or deleted anywhere on the website.

The following error occurs in the log if doing such an action in the BE:

Core: Error handler (BE): PHP Warning: require_once(/home/httpd/vhosts/netconsult.ch/dev.swissbaker.netconsult.ch/typo3conf/ext/netc_bakershop/Classes/Hooks/Hook.php): failed to open stream: No such file or directory in /home/httpd/vhosts/netconsult.ch/dev.swissbaker.netconsult.ch/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 4774 

**Please fix this immediately and very urgent!**

Please check it on the dev.swissbaker.netconsult.ch dev website: There is the same thing!!!

Thanks.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Status: Done
Screenshots:
Create News: BE: http://prntscr.com/ckhivv , FE: http://prntscr.com/ckhj0s
Edit News: BE: http://prntscr.com/ckhj95 , http://prntscr.com/ckhjkq , FE: http://prntscr.com/ckhjna
Delete News : BE: http://prntscr.com/ckhjtx , http://prntscr.com/ckhjxj

Comment: We have found that following folders with files were not present in the Extension package that we have provided. 
1. /typo3conf/ext/netc_bakershop/Classes/Hooks
2. /typo3conf/ext/netc_bakershop/Classes/XClasses

And they were also not present in the Github Repository. For now we have uploaded the latest files over there. But please make sure the complete extension package is there while you upload/change any files.

Don't hesitate to ask if you have any queries.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

Thanks. 

How was it possible that those files were NOT present on GitHub?

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your message.

FYI, Correction in my last comment - Only this file was not present in the GitHub - 2. /typo3conf/ext/netc_bakershop/Classes/XClasses
But both were not present in the Dev server that's why error was there.

And may be we have missed to upload this folder to the GitHub - 2. /typo3conf/ext/netc_bakershop/Classes/XClasses
that's why it's not there. 

But from next time we will take care about the package. And please also check all files are there on the testing server from the package. In this case on the Dev server files were not present.

Don't hesitate to ask if you have any queries.
Regards.
