### ISSUE TITLE
Subtotal and VAT are wrong

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#8]
Hi

Check out this screenshot:
http://screencast.com/t/9z1i7Ft9hcqV

1. The subtotal in the cart is wrong. It should be CHF 534 instead of CHF 540. 
2. The total amount in the e-mail confirmation seems correct, but the VAT is wrong. The total amount is 617 and VAT is shown as 45.7. But 8% of 617 are 49.40 (rounded).

Can you have a look into that and fix it?

I tested this on dev.swissbaker.netconsult.ch a few minutes ago.

**Comment by jigneshnitsan** [comment]
Hello Michel

1. Cart total is wrong
Comment > May be it's caching issues because here we show proper sub total
- http://awesomescreenshot.com/04e61xcb1e
- http://awesomescreenshot.com/07d61xcd3f
Can you please check it again by clearing cache?

2. VAT Calculation is not correct.
Comment > We think this is correct, for example
we have final total is 543.00 so this total is included VAT 8%
so to find actual vat we must follow formula like
  = (100*543.00)/108 = 502.78
  = 543.00-502.78
  = 40.22
so we get 40.22 [vat on actual amount]

and as you suggest (543.00*8)/100 gives 43.44 it's vat of final amount [543.00].

Please let me know if I am wrong and need any changes related it.

Regards.
Thank You.

**Comment by michelrossier** [comment]
The caching issue is odd, but we could not reproduce the problem after emptying all caches, so we leave it as it is. Thanks.

You are perfectly right, the VAT is calculated correct. I was under the assumption, that the vat is not included in the shop prices and added at the end. So your calculation is correct. Sorry for my mistake!
